spring:
  datasource:
    url: jdbc:mariadb://localhost:3308/hellofit_db
    username: hellofit_user
    password: 1q2w3e4r
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

server:
  port: 8082


jwt:
  secret: your-256-bit-secret-key
  expiration: 36000000