spring:
    config:
        import: aws-secretsmanager:hellofit/prod/db

    profiles:
        active: prod  # 기본은 dev로 실행(서버/CI에서 prod로 덮어쓰기)

server:
    port: 8084
    servlet:
        context-path: /api

# CORS는 환경별 yml에서 채우고, 여기서는 키만 둔다(빈 값이면 나중에 채워짐).
cors:
    allowed-origins: [ ]
    allowed-methods: [ GET, POST, PUT, PATCH, DELETE, OPTIONS ]
    allowed-headers: [ "*" ]
    exposed-headers: [ Authorization, Location ]
    allow-credentials: true
    max-age: 3600
