version: '3.8'

services:
    mariadb:
        image: mariadb:11
        container_name: mariadb_container
        environment:
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
            MARIADB_DATABASE: ${MARIADB_DATABASE}
            MARIADB_USER: ${MARIADB_USER}
            MARIADB_PASSWORD: ${MARIADB_PASSWORD}
        ports:
            - "3308:3306"
        volumes:
            - mariadb_data:/var/lib/mysql

volumes:
    mariadb_data:
