spring:
    datasource:
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        driver-class-name: org.h2.Driver
        username: sa
        password:

    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: false
        properties:
            hibernate:
                format_sql: true

    flyway:
        enabled: false

    cloud:
        aws:
            s3:
                enabled: false
            credentials:
                access-key: dummy
                secret-key: dummy
            region:
                static: ap-northeast-2

jwt:
    secret: test-secret-key
    expiration: 36000000

hellofit:
    security:
        pepper: test-pepper
