spring:
    config:
        activate:
            on-profile: dev

    cloud:
        aws:
            region:
                static: ap-northeast-2
            s3:
                enabled: true
                bucket: hellofit-bucket-test
            credentials:
                access-key: ${AWS_ACCESS_KEY} # sdk에서 자동으로 가져옴
                secret-key: ${AWS_SECRET_KEY}
            secretsmanager:
                enabled: false   # dev에서는 끄기

    datasource:
        url: jdbc:mariadb://localhost:3308/hellofit_db
        username: hellofit_user
        password: ${password}
        driver-class-name: org.mariadb.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: none

        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database-platform: org.hibernate.dialect.MariaDBDialect
    #        open-in-view: false

    flyway:
        enabled: true
        baseline-on-migrate: false   # 기존 DB 있을 때 기준선 생성
        validate-on-migrate: true
        locations: classpath:db/migration

    mvc:
        throw-exception-if-no-handler-found: true
    web:
        resources:
            add-mappings: false

cors:
    allowed-origins:
        - http://localhost:3000
        - http://localhost:3001

springdoc:
    api-docs:
        enabled: true        # API Docs(JSON) 노출 여부 (기본 true, 운영 배포 시 false로 막기도 함)
    swagger-ui:
        enabled: true        # Swagger UI 노출 여부
        operations-sorter: alpha   # API 정렬 (alpha: 알파벳순, method: HTTP 메서드순)
        tags-sorter: alpha
        doc-expansion: list   # UI에서 API 펼침 여부 (none, list, full)
    writer-with-default-pretty-printer: true   # JSON 스펙 출력 시 보기 좋게
    use-return-type-schema: true

jwt:
    secret: ${jwt_secret}    # 운영은 반드시 환경변수로
    expiration: 36000000

hellofit:
    security:
        pepper: ${password_pepper}
